export const Item = [
    {   
        "id": 1,
        "userId": "BE/17T/1/test23",
        "title": "Mrs",
        "Fullname": "Felixgggg",
        "center": "Maharagama",
        "course": "BED",
        "firstStage1": 55,
        "firstStage2": 14,
        "firstStage3": 23,
        "totalFStagemarks": 50,
        "firstStagePercentage":20,
        "secondStage1":30,
        "secondStage2":30,
        "totalsecondStagemarks": 40,
        "secondStagePercentage":20,
        "finalMarks": 80,
        "eligibleStatus": "Uneligible"
    },
    {
        "id": 2,
        "userId": "BE/17T/1/test24",
        "title": "Mrs",
        "Fullname": "cc",
        "center": "Maharagama",
        "course": "BED",
        "firstStage1": 55,
        "firstStage2": 14,
        "firstStage3": 23,
        "totalFStagemarks": 50,
        "firstStagePercentage":20,
        "secondStage1":30,
        "secondStage2":30,
        "totalsecondStagemarks": 40,
        "secondStagePercentage":20,
        "finalMarks": 80,
        "eligibleStatus": "Uneligible"
    },
    {
        "id": 3,
        "userId": "BE/17T/1/test25",
        "title": "Mrs",
        "Fullname": "vv",
        "center": "Maharagama",
        "course": "BED",
        "firstStage1": 55,
        "firstStage2": 14,
        "firstStage3": 23,
        "totalFStagemarks": 50,
        "firstStagePercentage":20,
        "secondStage1":30,
        "secondStage2":30,
        "totalsecondStagemarks": 40,
        "secondStagePercentage":20,
        "finalMarks": 80,
        "eligibleStatus": "Uneligible"
    },
    {
        "id": 4,
        "userId": "BE/17T/1/test26",
        "title": "Mrs",
        "Fullname": "bb",
        "center": "Maharagama",
        "course": "BED",
        "firstStage1": 55,
        "firstStage2": 14,
        "firstStage3": 23,
        "totalFStagemarks": 50,
        "firstStagePercentage":20,
        "secondStage1":30,
        "secondStage2":30,
        "totalsecondStagemarks": 40,
        "secondStagePercentage":20,
        "finalMarks": 80,
        "eligibleStatus": "Uneligible"
    },
    {
      "id": 5,
      "userId": "BE/17T/1/test27",
      "title": "Mrs",
      "Fullname": "aa",
      "center": "Maharagama",
      "course": "BED",
      "firstStage1": 55,
      "firstStage2": 14,
      "firstStage3": 23,
      "totalFStagemarks": 50,
      "firstStagePercentage":20,
      "secondStage1":30,
      "secondStage2":30,
      "totalsecondStagemarks": 40,
      "secondStagePercentage":20,
      "finalMarks": 80,
      "eligibleStatus": "Uneligible",
    },
    {   
        "id": 6,
        "userId": "BE/17T/1/test23",
        "title": "Mrs",
        "Fullname": "Felixgggg",
        "center": "Maharagama",
        "course": "BED",
        "firstStage1": 55,
        "firstStage2": 14,
        "firstStage3": 23,
        "totalFStagemarks": 50,
        "firstStagePercentage":20,
        "secondStage1":30,
        "secondStage2":30,
        "totalsecondStagemarks": 40,
        "secondStagePercentage":20,
        "finalMarks": 80,
        "eligibleStatus": "Uneligible"
    },
    {
        "id": 7,
        "userId": "BE/17T/1/test24",
        "title": "Mrs",
        "Fullname": "cc",
        "center": "Maharagama",
        "course": "BED",
        "firstStage1": 55,
        "firstStage2": 14,
        "firstStage3": 23,
        "totalFStagemarks": 50,
        "firstStagePercentage":20,
        "secondStage1":30,
        "secondStage2":30,
        "totalsecondStagemarks": 40,
        "secondStagePercentage":20,
        "finalMarks": 80,
        "eligibleStatus": "Uneligible"
    },
    {
        "id": 8,
        "userId": "BE/17T/1/test25",
        "title": "Mrs",
        "Fullname": "vv",
        "center": "Maharagama",
        "course": "BED",
        "firstStage1": 55,
        "firstStage2": 14,
        "firstStage3": 23,
        "totalFStagemarks": 50,
        "firstStagePercentage":20,
        "secondStage1":30,
        "secondStage2":30,
        "totalsecondStagemarks": 40,
        "secondStagePercentage":20,
        "finalMarks": 80,
        "eligibleStatus": "Uneligible"
    },
    {
        "id": 9,
        "userId": "BE/17T/1/test26",
        "title": "Mrs",
        "Fullname": "bb",
        "center": "Maharagama",
        "course": "BED",
        "firstStage1": 55,
        "firstStage2": 14,
        "firstStage3": 23,
        "totalFStagemarks": 50,
        "firstStagePercentage":20,
        "secondStage1":30,
        "secondStage2":30,
        "totalsecondStagemarks": 40,
        "secondStagePercentage":20,
        "finalMarks": 80,
        "eligibleStatus": "Uneligible"
    },
    {
      "id": 10,
      "userId": "BE/17T/1/test27",
      "title": "Mrs",
      "Fullname": "aa",
      "center": "Maharagama",
      "course": "BED",
      "firstStage1": 55,
      "firstStage2": 14,
      "firstStage3": 23,
      "totalFStagemarks": 50,
      "firstStagePercentage":20,
      "secondStage1":30,
      "secondStage2":30,
      "totalsecondStagemarks": 40,
      "secondStagePercentage":20,
      "finalMarks": 80,
      "eligibleStatus": "Uneligible",
    }
    

    ]